- id: ovs_install_compute
  type: puppet
  version: 2.1.0
  groups: [compute]
  requires: [allocate_hugepages]
  required_for: [netconfig]
  condition:
    yaql_exp: changed($.get('fuel-plugin-ovs'), $.get("hugepages", []))
  parameters:
    puppet_manifest: puppet/manifests/ovs-install-compute.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 720
